spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: batch
    password: batch
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create-drop